on:
  push:
    branches:
      - main
    paths:
      - "lg/**"
      - ".github/workflows/lg.yaml"
  pull_request:
    paths:
      - "lg/**"
      - ".github/workflows/lg.yaml"

name: Continuous integration

# Golang
jobs:
  check:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lg
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: lg/go.mod
          cache-dependency-path: lg/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
          working-directory: lg

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lg
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: lg/go.mod
          cache-dependency-path: lg/go.sum
      - name: Test
        run: go test -v ./...
